#!/bin/bash
    printf "Baleine est un outil simple de gestion de conteneur.\n"
    printf "Utilisation: \n \n"

    printf "NOM \n"
    printf "\t Image\n"
    printf "SYNOPSIS \n"
    printf "\t baleine image <COMMANDES> [arguments]\n"
    printf "Description: \n \n"
    printf "\t La commande 'image' permet de créer une image, en supprimer, lister les images existantes (Son nom, sa taille, son chemin ) \n" 
    printf "Les commandes sont :\n \n"
    printf "\t %-10s %-10s \n" "<create>"  "crée une image."
    printf "\t \t [-i], [NOM_IMAGE]\n \n" 
    printf "\t \t [-s], [TAILLE]\n \n" 
    printf "\t \t [-r], [REPERTOIRE]\n \n" 
    printf "\t \t [-P], [PROXY]\n \n"
    printf " \t %-10s %-10s \n" "<list>"  "liste les images existantes ainsi que leurs manifestes."
    printf " \t %-10s %-10s \n" "<remove>"  "Supprime l'image donnée en argument."
    printf "\t \t [-c], --container [NOM_CONTAINER]\n \n" 
    
    printf "NOM \n"
    printf "\t Bridge\n"
    printf "SYNOPSIS \n"
    printf "\t baleine bridge <COMMANDES> [arguments]\n"
    printf "Description: \n \n"
    printf "\t La commande 'bridge' permet de créer des bridges Linux, en supprimer et lister les bridges existants (Nom) \n" 
    printf "Les commandes sont :\n \n"
    printf "\t %-10s %-10s \n" "<create>"  "crée un bridge."
    printf "\t \t [-b], [NOM_BRIDGE]\n \n" 
    printf "\t \t [-a], [ADDR_IPV4]\n \n" 
    printf " \t %-10s %-10s \n" "<list>"  "liste les bridges existants ainsi que leurs manifestes."
    printf " \t %-10s %-10s \n" "<remove>"  "Supprime le bridge donné en argument."
    printf "\t \t [-b], --bridge [NOM_BRIDGE]\n \n"
    printf " \t %-10s %-10s \n" "<up>"  "Met up le bridge donné en argument."
    printf "\t \t [-b], --bridge [NOM_BRIDGE]\n \n"
    printf " \t %-10s %-10s \n" "<down>"  "Met down le bridge donné en argument."
    printf "\t \t [-b], --bridge [NOM_BRIDGE]\n \n"

    printf "NOM\n"
    printf "\t Container\n"
    printf "SYNOPSIS \n"
    printf "\t baleine container <COMMANDES> [arguments]\n"
    printf "Description: \n \n"
    printf "\t La commande 'Container' permet de créer des conteneurs, en supprimer, lister les conteneurs existants (Son nom, son image, son bridge, son PID, son starting time ) \n" 
    printf "Les commandes sont :\n \n"
    printf "\t %-10s %-10s \n" "<create>"  "crée un conteneur."
    printf "\t \t [-i], [NOM_IMAGE]\n \n" 
    printf "\t \t [-c], [NOM_CONTAINER]\n \n"
    printf "\t \t [-b], [NOM_BRIDGE]\n \n"
    printf "\t \t [-r], [REPERTOIRE]\n \n"
    printf "\t \t [-a], [ADDRE_IPV4]\n \n"
    printf "\t \t [-p], [NOM_PROGRAMME]\n \n"
    printf " \t %-10s %-10s \n" "<list> "  "liste les conteneurs existants ainsi que leurs manifestes."
    printf " \t %-10s %-10s \n" "<remove> "  "Supprime le conteneur donné en argument."
    printf "\t \t [-c], --container [NOM_CONTAINER]\n \n" 
    printf "\t \t %-10s %-10s \n" "<exec> "  "Exécute au lancement du conteneur un bash."
    printf "\t \t [-c], --container [NOM_CONTAINER]\n \n" 
    printf "\t %-10s %-10s \n" "<stop> "  "Stop le conteneur donné en argument."
    printf "\t \t [-c], --container [NOM_CONTAINER]\n \n" 
    
    


